### ISSUE TITLE
Investigate crashes when on webr oom

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#455]
For example: https://sbashevkin.r-universe.dev/LTMRdata

http://localhost:3000/cran/LTMRdata/data/Salvage/json

```
RuntimeError: table index is out of bounds
    at wasm://wasm/016c52ee:wasm-function[3024]:0x224c52
    at wasm://wasm/016c52ee:wasm-function[1787]:0x19550d
    at wasm://wasm/016c52ee:wasm-function[1773]:0x190fbb
    at wasm://wasm/016c52ee:wasm-function[1798]:0x196834
    at wasm://wasm/016c52ee:wasm-function[1624]:0x182009
    at new RVectorAtomic (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:2863:27)
    at new _RCharacter (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:3086:5)
    at newObjectFromData (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:2186:12)
    at new _RObject (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:2250:14)
    at REnvironment.slice_fn (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:2382:17)
```

```
UNCAUGHT EXCEPTION] RuntimeError: memory access out of bounds
    at wasm://wasm/016c52ee:wasm-function[1618]:0x181ea1
    at wasm://wasm/016c52ee:wasm-function[1792]:0x195c91
    at wasm://wasm/016c52ee:wasm-function[1266]:0x1612d4
    at new REnvironment (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:2783:35)
    at captureR (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:4921:21)
    at evalR (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:5013:19)
    at SharedBufferChannelWorker.dispatch (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:4581:28)
    at SharedBufferChannelWorker.inputOrDispatch (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:3833:37)
    at Object.readConsole (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/webr-worker.js:5098:19)
    at 1109299 (/Users/jeroen/workspace/r-universe/cranlike-server/node_modules/@r-universe/webr/dist/R.bin.js:1874:43769)
```

**Comment by jeroen** [comment]
Upstream issue -> https://github.com/r-wasm/webr/issues/464

**Comment by jeroen** [comment]
Should also refactor such that one webr export does not block others ones. Perhaps just use a single webR session that has all the packages preloaded after all.
