### ISSUE TITLE
App installation consistently errors

### ISSUE THREAD

**Issue by KaiAragaki** [r-universe-org/help#505]
Hello!

I'm trying to set up my own universe. I already *kind of* have a universe, since I have a single package on CRAN, but wanted to add my non-CRAN packages to it as well. I tried reinstalling the app after making a `packages.json` in the appropriate repository (https://github.com/KaiAragaki/kaiaragaki.r-universe.dev), but upon installation I get redirected to a page with the following error:

```
R-universe error!

Page not found: /_global/welcome

Stack trace

NotFoundError: Page not found: /_global/welcome
    at file:///frontend/app.js:53:8
    at Layer.handle [as handle_request] (/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/frontend/node_modules/express/lib/router/index.js:328:13)
    at /frontend/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/frontend/node_modules/express/lib/router/index.js:346:12)
    at next (/frontend/node_modules/express/lib/router/index.js:280:10)
    at /frontend/node_modules/express/lib/router/index.js:646:15
    at next (/frontend/node_modules/express/lib/router/index.js:265:14)
    at Function.handle (/frontend/node_modules/express/lib/router/index.js:175:3)
    at router (/frontend/node_modules/express/lib/router/index.js:47:12)

Server mode: production

If this seems like a bug and keeps happening, please report to: https://github.com/r-universe-org/help
```

Perhaps related, but the R-universe sync action appears not to be running on my repositories of interest, either.

This might be a me problem rather than an R-universe problem. Thank you!

**Comment by jeroen** [comment]
Thanks! Sorry that is a bug, should update the welcome page :)

**Comment by KaiAragaki** [comment]
Thanks for checking it out! Do you think this is unrelated to the failure to sync issues?

**Comment by jeroen** [comment]
The sync should work now, ill try to fix the welcome page asap. Thanks for reporting this
