### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#523]
```
anlike1  | GET /moseleybioinformaticslab/ScanCentricPeakCharacterization/doc/manual.html 200 1814.698 ms - 148217
cranlike1  | [Debug] HTTP 400: Error: Writable stream closed prematurely
cranlike1  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
cranlike1  |     at ServerResponse.setHeader (node:_http_outgoing:699:11)
cranlike1  |     at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
cranlike1  |     at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
cranlike1  |     at done (/app/node_modules/express/lib/response.js:1045:10)
cranlike1  |     at exports.renderFile (/app/node_modules/pug/lib/index.js:448:12)
cranlike1  |     at exports.__express [as engine] (/app/node_modules/pug/lib/index.js:493:11)
cranlike1  |     at View.render (/app/node_modules/express/lib/view.js:135:8)
cranlike1  |     at tryRender (/app/node_modules/express/lib/application.js:657:10)
cranlike1  |     at Function.render (/app/node_modules/express/lib/application.js:609:3)
cranlike1  |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1049:7)
cranlike1  |     at file:///app/node_modules/cranlike/app.js:57:7
cranlike1  |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
cranlike1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
cranlike1  |     at /app/node_modules/express/lib/router/index.js:286:9
cranlike1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
cranlike1  |     at next (/app/node_modules/express/lib/router/index.js:280:10)
```

**Comment by jeroen** [comment]
Can't repro this anymore. Maybe it was a glitch because the db connection. Hopefully express 5 will get better stack traces.
